export const courses: string[] = [
  // Fachbereich Biologie, Chemie, Pharmazie
  'Biochemie',
  'Biologie',
  'Biologie Lehramt',
  'Chemie',
  'Chemie Lehramt',
  'Pharmazie',
  // Fachbereich Erziehungswissenschaft & Psychologie
  'Bildungs- und Erziehungswissenschaft',
  'Grundschulpädagogik',
  'Psychologie',
  'Sonderpädagogik',
  // Fachbereich Geowissenschaften
  'Geographische Wissenschaften',
  'Geologische Wissenschaften',
  'Meteorologie',
  // Fachbereich Geschichts- und Kulturwissenschaften
  'Altertumswissenschaften: Profilbereich Altorientalistik',
  'Altertumswissenschaften: Profilbereich Klassische Archäologie',
  'Altertumswissenschaften: Profilbereich Prähistorische Archäologie',
  'Altertumswissenschaften: Profilbereich Vorderasiatische Archäologie',
  'Altertumswissenschaften: Profilbereich Ägyptologie',
  'Altorientalistik',
  'Ägyptische Archäologie',
  'Ägyptische Philologie',
  'Ägyptologie',
  'Chinastudien',
  'Chinastudien/Ostasienwissenschaft',
  'Chinesisch',
  'Chinesische Sprache und Gesellschaft',
  'Chinesische Sprache und Gesellschaft Lehramt',
  'Geschichte',
  'Geschichte Lehramt',
  'Geschichte und Kultur des Vorderen Orients',
  'Geschichte und Kultur des Vorderen Orients: Schwerpunktbereich Arabistik',
  'Geschichte und Kultur des Vorderen Orients: Schwerpunktbereich Iranistik',
  'Geschichte und Kultur des Vorderen Orients: Schwerpunktbereich Islamwissenschaft',
  'Geschichte und Kultur des Vorderen Orients: Schwerpunktbereich Semitistik',
  'Geschichte und Kultur des Vorderen Orients: Schwerpunktbereich Turkologie',
  'Hebräische Sprache',
  'Japanisch',
  'Japanstudien',
  'Japanstudien/Ostasienwissenschaften',
  'Judaistik',
  'Jüdische Geschichte',
  'Klassische Archäologie',
  'Koreanisch',
  'Koreastudien',
  'Koreastudien/Ostasienwissenschaften',
  'Kunstgeschichte Afrikas',
  'Kunstgeschichte mit dem Schwerpunkt Afrika',
  'Kunstgeschichte mit dem Schwerpunkt Europa und Amerika',
  'Kunstgeschichte mit dem Schwerpunkt Ostasien',
  'Kunstgeschichte, Europa und Amerika',
  'Kunstgeschichte, Ostasatische',
  'Prähistorische Archäologie',
  'Religionswissenschaft',
  'Vorderasiatische Archäologie',
  // Fachbereich Mathematik und Informatik
  'Bioinformatik',
  'Informatik',
  'Informatik Lehramt',
  'Mathematik',
  'Mathematik Lehramt',
  // Fachbereich Philosophie und Geisteswissenschaften
  'Allg. und Vergl. Literaturwissenschaft',
  'Byzantinistik',
  'Deutsch-Französische Literatur- und Kulturstudien',
  'Deutsche Philologie',
  'Deutsche Philologie Lehramt',
  'Englische Philologie',
  'Englische Philologie Lehramt',
  'Filmwissenschaft',
  'Frankreichstudien',
  'Französisch',
  'Französische Philologie',
  'Französische Philologie Lehramt',
  'Galicische Sprache und Kultur',
  'Griechische Literatur in Übersetzung',
  'Griechische Philologie',
  'Griechische Philologie Lehramt',
  'Italienisch',
  'Italienische Philologie',
  'Italienische Philologie Lehramt',
  'Italienstudien',
  'Katalanische Sprache und Kultur',
  'Lateinische Philologie',
  'Lateinische Philologie Lehramt',
  'Mittellateinische Philologie',
  'Neogräzistik',
  'Neugriechische Sprache und Kultur',
  'Niederländische Philologie',
  'Philosophie',
  'Philosophie Lehramt',
  'Portugiesisch-Brasilianische Studien',
  'Spanisch',
  'Spanische Philologie mit Lateinamerikanistik',
  'Spanische Philologie mit Lateinamerikanistik Lehramt',
  'Sprache & Gesellschaft',
  'Sprachen der Klassischen Antike - Griechisch',
  'Sprachen der Klassischen Antike - Latein',
  'Theaterwissenschaft',
  // Fachbereich Physik
  'Physik',
  'Physik Lehramt',
  // Fachbereich Politik- und Sozialwissenschaften
  'Medieninformatik',
  'Politikwissenschaft',
  'Politikwissenschaft Lehramt',
  'Publizistik- und Kommunikationswissenschaft',
  'Sozial- und Kulturanthropologie',
  // Fachbereich Rechtswissenschaft
  'Rechtswissenschaft',
  // Fachbereich Veterinärmedizin
  'Pferdewissenschaft',
  'Veterinärmedizin',
  // Fachbereich Wirtschaftswissenschaft
  'Betriebswirtschaftslehre',
  'Management',
  'Volkswirtschaftslehre',
  // Medizinische Fakultät Charité - Universitätsmedizin Berlin
  'Gesundheitswissenschaft',
  'Medizin',
  'Zahnheilkunde',
  // Zentralinstitut John-F.-Kennedy-Institut für Nordamerikastudien
  'Angewandte Nordamerikastudien',
  'Nordamerikastudien',
  // Zentralinstitut Lateinamerika-Institut
  'Lateinamerikastudien',
];
